## Assignment 1

**Instructions:** <br>
a. write your answer after `# your answer here`. Do not delete any code that is in the cell, as the code facilitates checking your answers. If you happen to delete any code that prevents expected outputs, you may lose points. <br>
b. when you finish the assignment, make sure to use `Kernel` -> `Restart and Run All` to restart the kernel and rerun the entire notebook to generate the desired outputs, before submitting your assignment. <br>
c. upload your .ipynb file. <br>
<br>
Each question is worth 5 points.
### Python Types and Functions

1. Write a function to check if a given key (input1) already exists in a dictionary (input2), if true, return a tuple of the key and the value; if false, return None.

In [1]:
fruits = {'apple': 'red', 'pear': 'yellow', 'orange': 'orange', 'grape': 'purple'}
def is_key_present(input1, input2):
    # your answer here
    state = input1 in input2
    if state == True:
        x = (input1,fruits[input1])
        return x
    else:
        return None
    
print(is_key_present('pear', fruits))
print(is_key_present('watermelon', fruits))

('pear', 'yellow')
None


2. Create a function that takes a string as the input and returns a dictionary showing the number of characters in a string. <br>
Sample Input: 'apple pie' <br>
Output: {'a': 1, 'p': 3, 'l': 1, 'e': 2, ' ': 1, 'i': 1}

In [2]:
def char_frequency(string):
    # your answer here  
    char = {}
    string =string#.replace(" ","")
    for i in string:
        if i in char:
            char[i]+=1
        else:
            char[i]=1
    return char

print(char_frequency('apple pie')) 

{'a': 1, 'p': 3, 'l': 1, 'e': 2, ' ': 1, 'i': 1}


3. Create a function that takes a string as the input and return a string that is made of the first 2 and the last 2 characters of the input string. If the string length is less than 2, return 'The length of the input string is shorter than 2!'. <br>
Sample String : 'carnivore' <br>
Expected Result : 'care' <br>
Sample String : 'hi' <br>
Expected Result : 'hihi' <br>
Sample String : '?' <br>
Expected Result : 'The length of the input string is shorter than 2!'

In [3]:
def string_start2_end2(str):
    # your answer here
    count = len(str)
    if count <2:
        return 'The length of the input string is shorter than 2!'
    else:
        x = str[0:2]+str[-2:]
        return x
    
print(string_start2_end2('carnivore'))
print(string_start2_end2('hi'))
print(string_start2_end2('?'))

care
hihi
The length of the input string is shorter than 2!


4. Create a function that takes two inputs of lists and return an interwined list in this way: <br>
Sample input: <br>
listA = [1, 2, 3, 4]<br>
listB = ['a', 'b', 'c', 'd', 'e', 'f']<br>
Return:
[1, 'a', 2, 'b', 3, 'c', 4, 'd', 'e', 'f'].<br>
Note: when the lengths do not match, the remainder shall be appended to the end of the output list.

In [4]:
def interwine(A, B):
    # your answer here
    a = len(A)
    b = len(B)
    
    if a == b:
        return [i for pair in zip(A,B) for i in pair]    
    
    else:
        if a > b:
            return [i for pair in zip(A,B) for i in pair] + A[-(a-b):]
        else:
            return [i for pair in zip(A,B) for i in pair] + B[-(b-a):]
        
listA = [1, 2, 3, 4, 5]
listB = ['a', 'b', 'c', 'd', 'e', 'f']

print(interwine(listA, listB))
print(interwine(listB, listA))
print(interwine(listA, listA))

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 'f']
['a', 1, 'b', 2, 'c', 3, 'd', 4, 'e', 5, 'f']
[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]


### Lambda

5. Write a function to extract year, month and day from datetime using Lambda, and print using the string formatting.<br>
Sample input: 
now = 2020-09-10 22:24:17.072952<br>
Output: 'Year: 2020, month: 9, day: 10'<br> <br>

In [5]:
import datetime
now = datetime.datetime.now()
print(now)

def date_time(date):
    #use lambda to extract the information
    Year = lambda x: x.year
    Month = lambda x: x.month
    Day = lambda x: x.month
    
    #string formatting
    date_format='Year:{}, month:{}, day:{}'.format(Year(date),Month(date),Day(date))
    print(date_format)
    
date_time(now)

2022-10-07 20:24:57.403880
Year:2022, month:10, day:10


6. Sort a list of tuples by the second element using Lambda.<br>
Sample input: [('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)] <br>
Output: [('Banana', 0), ('Pear', 2), ('Apple', 12), ('Orange', 15)]

In [6]:
before = [('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)]

# Use lambda to create an output list: your answer here
after = sorted(before, key=lambda x:x[1])

print("Original list of tuples:")
print(before)

print("\nSorted list of Tuples:")
print(after)

Original list of tuples:
[('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)]

Sorted list of Tuples:
[('Banana', 0), ('Pear', 2), ('Apple', 12), ('Orange', 15)]


7. Write a function to count the odd, even numbers in a given array of integers using Lambda. <br>
Sample input:  <br>
[1, 4, 3, 11, 7, 8, 15, 10]  <br>
Sample output:  <br>
Number of odd numbers: 5  <br>
Number of even numbers: 3  <br>

In [7]:
array_example = [1, 4, 3, 11, 7, 8, 15, 10]
def even_odd(array_numbers):
    # your answer here: variables 'odd' and 'even' are the counted numbers respectively
    odd = 0
    even = 0
    for i in array_numbers:
        if (i%2)==0:
            even+=1
        else:
            odd+=1
    
    print("Number of even numbers: ", even)
    print("Number of odd numbers: ", odd)

even_odd(array_example)

Number of even numbers:  3
Number of odd numbers:  5


### List Comprehension

8. Create a function that takes an input list of strings and returns (1) a list containing the length of each string and (2) a tuple containing the shortest string and its index in the list. <br>
Note: you shall use list comprehension in the function.<br> <br>
Sample input: ['I', 'love', 'programming', 'using', 'Python'] <br>
Return: ([1, 4, 11, 5, 6], ('I', 0)).

In [8]:
def find_shortest_word(words_list):
    
    # list comprehension
    word_no=[len(i) for i in words_list]

    # find the index of the shortest string
    pos = word_no.index(min(word_no))
    x = (words_list[pos],pos)

    return word_no , x

print(find_shortest_word(['I', 'love', 'programming', 'using', 'Python']))

([1, 4, 11, 5, 6], ('I', 0))


### Numpy

9. Use numpy and arange to create a 2x4 matrix with values ranging from 2 to 9. <br>
Ouput:<br>
Expected Output:<br>
[[ 2 3 4 5]<br>
[ 6 7 8 9]]

In [9]:
import numpy as np
# your answer here
print(np.arange(2,10).reshape(2,4))

[[2 3 4 5]
 [6 7 8 9]]


10. Write a function to take an integer numpy array as the input, then (1) create an array that has the same values as the input array, and if there are odd numbers, add 1 to change them to even numbers, (2) stack the input array and the new array vertically, and (3) change the array to the float type (i.e. 'float32'). <br>
Sample input:<br>
[ 1  5  7 12 14] <br>
Output: <br>
[[ 1.  5.  7. 12. 14.]<br>
 [ 2.  6.  8. 12. 14.]]

In [10]:
import numpy as np
example = np.array([1, 5, 7, 12, 14],dtype='int32')
print(example,'\n')

def array_func(a):
    # your answer here
    array = a.copy()
    array[(array%2)!=0]+=1
    x = np.vstack([example,array]).astype('float32')
    return x

result = array_func(example)
print(result.dtype)
print(result)

[ 1  5  7 12 14] 

float32
[[ 1.  5.  7. 12. 14.]
 [ 2.  6.  8. 12. 14.]]


11. Use numpy to first create a 6 by 6 matrix and fill it with a checkerboard pattern. Then append a column of 2's to the left. <br>
Checkerboard pattern:<br>
[[2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]                                                      
 [2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]                                                      
 [2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]]

In [11]:
import numpy as np
print("A checkerboard pattern with 2's on the left:")
# your answer here
x = np.zeros((6,6),dtype=int)
x[::,:1:] = 2
x[::2,2::2] = 1
x[1::2,1::2]=1
x

A checkerboard pattern with 2's on the left:


array([[2, 0, 1, 0, 1, 0],
       [2, 1, 0, 1, 0, 1],
       [2, 0, 1, 0, 1, 0],
       [2, 1, 0, 1, 0, 1],
       [2, 0, 1, 0, 1, 0],
       [2, 1, 0, 1, 0, 1]])

12. Write a function that obtains 2000 samples from normal distribution (mean=0, standard deviation=1) and calculate cosine for each of them. Then return an array that contains (1) the number of elements that is negative, (2) the mean, and (3) the 25th and 75th percentiles. Use numpy.round? to round your results to have three decimals. <br>
Sample output:<br>
array([234.   ,   0.619,   0.452,   0.954])<br>

In [12]:
import numpy as np
np.set_printoptions(suppress=True) 

def fun_cos():
    # your answer here
    sample = np.random.normal(loc = 0, scale = 1, size = 20)
    cos_sample = np.cos(sample)
    Neg_no=len(cos_sample[cos_sample<0])
    #cos_sample.mean()
    #np.percentile(cos_sample,25)
    #np.percentile(cos_sample,75)
    array = np.array([Neg_no,cos_sample.mean(),np.percentile(cos_sample,25),np.percentile(cos_sample,75)])
    return np.round(array,decimals=3)

np.random.seed(1234)
fun_cos()

array([2.   , 0.538, 0.34 , 0.925])